# Generated by Django 3.0 on 2020-10-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='therapyType',
        ),
    ]
