# Generated by Django 3.0 on 2020-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tracker_therapytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='therapyType',
            field=models.CharField(choices=[('item_key1', 'Chemotherapy'), ('item_key2', 'Radiation'), ('item_key3', 'Hormonal'), ('item_key4', 'Biological'), ('item_key5', 'Surgery')], default='item_key1', max_length=20),
        ),
    ]
