# Generated by Django 3.0 on 2020-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tracker_therapytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='therapyType',
            field=models.CharField(choices=[('Chemotherapy', 'Chemotherapy'), ('Radiation', 'Radiation'), ('Hormonal', 'Hormonal'), ('Biological', 'Biological'), ('Surgery', 'Surgery')], default='item_key1', max_length=20),
        ),
    ]
